### ISSUE TITLE
Add keyboard shortcut reference

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#1285]
Typing `?` on any page should bring up a keyboard shortcut cheatsheet.

See https://github.com/electron/search-with-your-keyboard/#behavior for existing shortcuts

**Comment by zeke** [comment]
A nice example from messages.android.com:

<img width="935" alt="screen shot 2018-06-27 at 8 31 45 pm" src="https://user-images.githubusercontent.com/2289/42006659-3a1390ce-7a49-11e8-919f-a6324c9542c3.png">

**Comment by snidelyhazel** [comment]
(Hi Zeke! I paired with Nhori on some of the "good first issue"-labeled issues on W/S/C Code Day. There were some that I'd found interesting/challenging that have been swirling in the back of my mind, so I decided to look into them.)

I tried the keyboard commands on electronjs.org. I could get all of them to work except for Ctrl/Cmd + Enter. Is it supposed to work or has it been disabled purposely? How can I trigger it?

Should this cheatsheet be a modal dialog as per the sample from messages.android.com? Are there any other example modal dialogs in the website yet?

**Comment by zeke** [comment]
> except for Ctrl/Cmd + Enter

I think that feature was added in a recent pull request that may not have made it to the website yet. https://github.com/electron/search-with-your-keyboard/pull/9

> Are there any other example modal dialogs in the website yet?

No I think this would be the first! :)

**Comment by snidelyhazel** [comment]
So one of the most common ways to implement a modal dialog is with Bootstrap, and I did see references to Jumbotron (a Bootstrap feature) but I think you're just using the concept of jumbotron rather than the Bootstrap implementation i.e. for the electronjs.org landing page. (Though I did see a shell script called bootstrap and got confused for a sec!)

Then I searched within Primer and Basecoat (which I realize is deprecated now in favor of Primer) but there didn't seem to be any preexisting features that I could build on for modal dialogs.

I'm currently experimenting on my branch in main.html, having added a new SCSS file for modal dialog styling and a Javascript file under scripts, based on the W3Schools implementation: https://www.w3schools.com/howto/howto_css_modals.asp

I could probably put modal dialog creation in a Handlebars template, similar to this CodePen example, if that would be more useful: https://codepen.io/informa/pen/ogBmLK

**Comment by snidelyhazel** [comment]
The keyboard handler is working!

Initially there was a conflict between the behavior of "/" and "?", as the keyboard behavior event handler for "/" was ignoring the Shift key and would interpret "?" as "/". But I resolved that by making sure that our event handler was handled first using the capture phase. If it determines that "?" is being pressed, it stops propagation so the existing event handler for the keyboard behaviors won't kick in. So it brings up the cheatsheet successfully, while allowing "?" to be typed into input fields, as well as any text to be entered into the search input field behind the modal.

I'm wondering if it would make sense to move any of this code into https://github.com/electron/search-with-your-keyboard/blob/master/index.js?

The other aspect I'd like your input on is making the display prettier! I used a similar color scheme to the search tools, though I'm unsure if there are specs I should be following re spacing.

Also please note that in trying to emulate the table on https://github.com/electron/search-with-your-keyboard/#behavior I don't have the cute key styling. I could either try to get the .markdown-body kbd styles from the readme working or use CSS to emulate it (kbd isn't deprecated but CSS is probably better longterm?).

![image](https://user-images.githubusercontent.com/30618085/43995806-9862bb52-9d6a-11e8-95be-ca8082751dd5.png)

**Comment by zeke** [comment]
👏 that is looking really nice!

Feel free to open a PR here and give it a `[WIP]` prefix so folks know it's a work in progress. That will make it easier to discuss what code should live where. :)

**Comment by zeke** [comment]
You will need to fork the repo, create a branch on your own fork, then create a pull request from your fork. See https://help.github.com/articles/fork-a-repo/

Since you've already cloned the project, you can just change the git remote in your `.git/config` file to the URL of your new fork.

**Comment by snidelyhazel** [comment]
I think I figured out how to do that just before I called it for the night.

Here's where I'm at now: https://github.com/electron/electronjs.org/pull/1309

Thanks again for all the help!

**Comment by HashimotoYT** [comment]
It's finished in #2088.
