### ISSUE TITLE
Add fiddle to top navbar for more visibility

### ISSUE THREAD

**Issue by co16353sidak** [electron/electronjs.org#2376]
Fiddle is an amazing resource for newcomers (like me) to work on electron with no setup worries, so I feel that it would serve the website better if we find a place for it on the navbar to make it more visible at the top for people to come in and have an option to enter into it straight away.

many platforms (like [nativescript](https://www.nativescript.org/getting-started-with-nativescript) with their playground app) follow the same convention and I feel we should follow the same.

**Comment by BinaryMuse** [comment]
Thanks for the suggestion, @co16353sidak. We're currently working on some CSS changes to the site and also exploring changing Fiddle so that it can better serve as a good first point of contact for API experimentation; once these things are done, we're going to explore giving it a more prominent position on the website.

**Comment by co16353sidak** [comment]
@BinaryMuse , roger that
Would love to work on those css changes you mentioned, are there any issues or any changes that can be taken up by users outside the core dev team (like me).
Would love to contribute as much as possible

**Comment by BinaryMuse** [comment]
@co16353sidak https://github.com/electron/electronjs.org/issues/2258 might be worth looking into, I'm not 100% certain. @HashimotoYT might have more info!

**Comment by HashimotoYT** [comment]
@co16353sidak Because I have 101% information about this, here answers. All migration and all pages tracking described in #2361. The issue what give you @BinaryMuse not describes how it's done now.

If you want to help I can offer "Community" page. For more information on how to do it, you can see in previous [PRs](https://github.com/electron/electronjs.org/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc+label%3Aready-for-review).

Sorry for creating some confusion about this.
