### ISSUE TITLE
Scrolling via Down-arrow put the focus on the search

### ISSUE THREAD

**Issue by vhashimotoo** [electron/electronjs.org#4108]
https://twitter.com/BMorearty/status/1273035753677676545

**Comment by naldossary** [comment]
Hi

**Comment by aryanshridhar** [comment]
Have been trying to fix this issue for a while now by adding custom focus to dropdown elements once the user presses the up/down arrow keys , but there are a number of issues arising because of the same. 
For example , the dropdown doesn't automatically scroll down once the focus exceeds the page (Tried tickling <code>tabindex</code> values but in vain ) 

Soon , I opened a <a href = 'https://github.com/algolia/instantsearch.js/discussions/4606'>discussion</a> in <a href = 'https://github.com/algolia/instantsearch.js/'>instantsearch.js</a> regarding the same issue and was suggested to use <a href = 'https://autocomplete.algolia.com/'>autocomplete</a> instead , since this feature was lacking in <code>instantsearch.js</code> . 

Should the search functionality in electron be re-modified as per <code>autocomplete</code> instead @vhashimotoo or is this feature not too important to shift from <code>instantsearch</code> to <code>autocomplete</code> ?
