### ISSUE TITLE
child_process.exec in electron doesn't work

### ISSUE THREAD

**Issue by mengsumin** [electron/electronjs.org#5733]
hai, i was used electronjs to make a desktop-print-app in window system.

it's main function is to generate data then print.

the gtxprinter only accept arxp-data, so i must transfer json config into arxp-data by child-process
here is my referent code

```
const cmdPath = './Print/'
const cmdStr = '.\\GTXproCMD.exe print -X "Profile\\profile.xml" -I "Input\\sample.png" -A "Output\\printData.arxp" -L 02540254 -R 0400'
const sendCmd = '.\\GTXproCMD.exe send -A "Output\\printData.arxp" -P "Brother GTX pro FileOutput" -D 1'
var child_process = require('child_process');
var iconv = require('iconv-lite');

var encoding = 'cp936';
var binaryEncoding = 'binary';

runExec();
function runExec() {
  console.log(cmdStr)
  console.log(cmdPath)
  child_process.exec(cmdStr, { encoding: binaryEncoding,cwd: cmdPath }, function(err, stdout, stderr){
    console.log(iconv.decode(Buffer.from(stdout, binaryEncoding), encoding), iconv.decode(Buffer.from(stderr, binaryEncoding), encoding));
});
}
```
it works well in node-environment alonely.
this cmd command is to gennerate arxp data in 'output' file
but when i after "npm run start "
it doesn't work. there is no body in output-file,  no error console, no tips, 
i tried to debug , the program can debuginto the handerFuntion. but just work.
i think is could cause dby electronjs 
the electron has node，there is no reason to run it but not working.

could some one help me？

**Comment by ckerr** [comment]
Hi @mengsumin,

I think you mean to send this bug report to `electron/electron` rather than this repo, which is about the website? :smile: 

You will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
