### ISSUE TITLE
Is it so difficult to write a documentation properly ?! – .pageRanges for printToPDF

### ISSUE THREAD

**Issue by projektorius96** [electron/electronjs.org#5905]
I was reading docs (reference) as usually & found myself asking even if I technically know the answer : "Why the heck we write tests, use TypeScript, etc." if we **simply cannot write docs properly** ? What is most important , I do understand thing such as (extended) **Backus Naur form** exists & it's actually does a great job most of the time i.e.: 0, 2 as values provided within example below go either as typeof number or string as suggested <number, string> (_correct me If I misinterpreted docs_), but let me ask you politely is it soooo difficult to "emphasize" that **pageRanges** is an **object** ?! Sorry, I see no high math into this, I simply don't ...

**Example**:
![image](https://user-images.githubusercontent.com/34185919/153780203-4979d3f0-e329-42d3-9ca2-2e00af1ff635.png)

Yours faithfully,
Ordinary Electronjs's user

**Comment by erickzhao** [comment]
Our docs operate with TypeScript types, where `Record<Keys, Type>` is always an object: https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type

**Comment by projektorius96** [comment]
Well I don't use TypeScript with reason, many others don't as well, especially who came from C lang family world . I can bet . It means your documentation follows TypeScript approach without any notice **e.g, on "How to Read the Docs" section** . Don't you find it kind of bizarre , or its because full stomach never understand the hunger which same as if I'd say Electron contributors / engineers / will never able to explain to ordinary babushka found on street . Your job is to react to user's complains & improve otherwise keep that Electron for yourself fellas !

**Comment by jkleinsc** [comment]
Open source is largely volunteer-driven and collaborative. Because of this, time and energy to get things done are often the scarcest resources. We want Electron to be the best that it can be, but we also have to be realistic about what the team maintaining Electron can achieve. This means that:

* We might not have an ETA for when an issue will get investigated or fixed.
* Something you want implemented might not get implemented.
* A change you want merged might not get merged.
* Insisting on or making demands for any of the above is considered against [the Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md)

@projektorius96 your comment was minimized as a violation of [the Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md). You may consider this an official warning.

**Please do not interact with the project for 24 hours.** After that, please look through your open issues and edit them to ensure they're entirely on-topic, and we can continue the discussion here about the best way to go forward.
